import os
from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.enum.text import PP_ALIGN
from pptx.dml.color import RGBColor
from pptx.enum.shapes import MSO_SHAPE

def generate_pitch_deck_ppt(plan_data: dict, file_path: str):
    """
    Generates a professional PowerPoint presentation with a custom theme
    from the startup plan data.
    """
    os.makedirs(os.path.dirname(file_path), exist_ok=True)
    prs = Presentation()
    
    # 16:9 Widescreen Aspect Ratio
    prs.slide_width = Inches(13.333)
    prs.slide_height = Inches(7.5)
    
    # Modern Color Palette
    bg_color = RGBColor(250, 250, 252)       # Light gray/off-white background
    accent_color = RGBColor(79, 70, 229)     # Indigo-600
    dark_text = RGBColor(31, 41, 55)         # Gray-800
    light_text = RGBColor(255, 255, 255)
    
    def add_background(slide):
        # Base background shape
        bg = slide.shapes.add_shape(MSO_SHAPE.RECTANGLE, 0, 0, prs.slide_width, prs.slide_height)
        bg.fill.solid()
        bg.fill.fore_color.rgb = bg_color
        bg.line.fill.background() # No border
        
        # Subtle accent bar at the bottom
        bar = slide.shapes.add_shape(MSO_SHAPE.RECTANGLE, 0, Inches(7.2), prs.slide_width, Inches(0.3))
        bar.fill.solid()
        bar.fill.fore_color.rgb = accent_color
        bar.line.fill.background()

    def add_header(slide, title_text):
        # Banner for header
        banner = slide.shapes.add_shape(MSO_SHAPE.RECTANGLE, 0, 0, prs.slide_width, Inches(1.2))
        banner.fill.solid()
        banner.fill.fore_color.rgb = accent_color
        banner.line.fill.background()
        
        txBox = slide.shapes.add_textbox(Inches(0.5), Inches(0.25), Inches(12.333), Inches(0.7))
        tf = txBox.text_frame
        p = tf.paragraphs[0]
        p.text = title_text
        p.font.bold = True
        p.font.size = Pt(36)
        p.font.color.rgb = light_text
        p.font.name = "Arial"

    def add_content(slide, content_text):
        # Add content text box
        txBox = slide.shapes.add_textbox(Inches(0.5), Inches(1.5), Inches(12.333), Inches(5.5))
        tf = txBox.text_frame
        tf.word_wrap = True
        
        p = tf.paragraphs[0]
        # Truncate content slightly to fit if too long, though layout depends on exact text
        p.text = str(content_text)[:1500] + ("..." if len(str(content_text)) > 1500 else "")
        p.font.size = Pt(20)
        p.font.color.rgb = dark_text
        p.font.name = "Arial"
        p.alignment = PP_ALIGN.LEFT
        p.line_spacing = 1.3

    blank_slide_layout = prs.slide_layouts[6]
    
    # ─── 1. Title Slide ───
    slide = prs.slides.add_slide(blank_slide_layout)
    
    # Solid accent background for title
    bg = slide.shapes.add_shape(MSO_SHAPE.RECTANGLE, 0, 0, prs.slide_width, prs.slide_height)
    bg.fill.solid()
    bg.fill.fore_color.rgb = accent_color
    bg.line.fill.background()
    
    txBox = slide.shapes.add_textbox(Inches(1), Inches(2.5), Inches(11.333), Inches(2))
    tf = txBox.text_frame
    p = tf.paragraphs[0]
    p.text = plan_data.get('startup_title', 'Startup Pitch Deck')
    p.font.bold = True
    p.font.size = Pt(60)
    p.font.color.rgb = light_text
    p.font.name = "Arial"
    p.alignment = PP_ALIGN.CENTER
    
    p2 = tf.add_paragraph()
    p2.text = "Generated by AutoStartup AI"
    p2.font.size = Pt(28)
    p2.font.color.rgb = RGBColor(200, 200, 255)
    p2.font.name = "Arial"
    p2.alignment = PP_ALIGN.CENTER
    p2.space_before = Pt(20)
    
    # ─── 2. The Problem ───
    slide = prs.slides.add_slide(blank_slide_layout)
    add_background(slide)
    add_header(slide, "The Problem & Target Audience")
    problem_text = f"Problem Statement:\n{plan_data.get('problem_statement', 'N/A')}\n\nTarget Audience:\n{plan_data.get('target_audience', 'N/A')}"
    add_content(slide, problem_text)

    # ─── 3. The Solution ───
    slide = prs.slides.add_slide(blank_slide_layout)
    add_background(slide)
    add_header(slide, "The Solution")
    add_content(slide, plan_data.get('solution', 'N/A'))

    # ─── 4. Core Features ───
    slide = prs.slides.add_slide(blank_slide_layout)
    add_background(slide)
    add_header(slide, "Core Features")
    add_content(slide, plan_data.get('core_features', 'N/A'))

    # ─── 5. Market Gap ───
    slide = prs.slides.add_slide(blank_slide_layout)
    add_background(slide)
    add_header(slide, "Market Gap & Opportunity")
    add_content(slide, plan_data.get('market_gap', 'N/A'))

    # ─── 6. Business Model ───
    slide = prs.slides.add_slide(blank_slide_layout)
    add_background(slide)
    add_header(slide, "Business & Revenue Model")
    add_content(slide, plan_data.get('revenue_model', 'N/A'))

    # ─── 7. Roadmap ───
    slide = prs.slides.add_slide(blank_slide_layout)
    add_background(slide)
    add_header(slide, "Implementation Roadmap")
    add_content(slide, plan_data.get('implementation_roadmap', 'N/A'))

    # Save
    prs.save(file_path)
